Repository wakatime/desktop, pull requests merged in 2019-10, with the labels that each got.

#55 fix terminal tests
  test/terminal.spec.ts
Labels: bug

#56 remove deprecated code, and fix loading editors
  .travis.yml
  src/editors/android-studio.ts
  src/editors/appcode.ts
  src/editors/editor.ts
  src/editors/sublime-text-3.ts
  src/editors/terminal.ts
Labels: bug, cleanup, enhancement

#58 fix loop over arrays
  src/editors/android-studio.ts
  src/editors/atom.ts
  src/editors/blender.ts
  src/editors/coda.ts
  src/editors/editor.ts
  src/editors/sublime-text-3.ts
  src/editors/vim.ts
  src/editors/vscode.ts
  src/editors/xcode.ts
Labels: bug

#59 add jetbrains editors: datagrip, goland, intellij, phpstorm, pycharm
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/datagrip.ts
  src/editors/goland.ts
  src/editors/intellij.ts
  src/editors/phpstorm.ts
  src/editors/pycharm.ts
  src/editors/rider.ts
  test/datagrip.spec.ts
  test/goland.spec.ts
  test/intellij.spec.ts
  test/phpstorm.spec.ts
  test/pycharm.spec.ts
  test/rider.spec.ts
Labels: help wanted, planned

#60 add azure data studio editor
  src/components/ActiveEditors.tsx
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/constants/imgPaths.ts
  src/editors/azure-data-studio.ts
  src/imgs/editor-icons/azure-data-studio-128.png
  test/azure-data-studio.spec.ts
Labels: planned

#63 Terminal editor
  src/editors/azure-data-studio.ts
  src/editors/coda.ts
  src/editors/terminal.ts
Labels: cleanup, feature, planned

#64 intellij installPlugin and uninstallPlugin implemented
  src/editors/intellij.ts
  src/utils/jetbrains.ts
Labels: cleanup, enhancement, planned

#66 add netbeans, isEditorInstalled, isPluginInstalled and test it
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/netbeans.ts
  test/netbeans.spec.ts
Labels: feature, planned

#67 textmate isEditorInstalled and isPluginInstalled working
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/textmate.ts
  test/textmate.spec.ts
Labels: feature, planned

#68 add Gedit editor
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/gedit.ts
  test/android-studio.spec.ts
  test/gedit.spec.ts
Labels: feature, planned

#69 add wakatime tray icon, remove binaries functions that we dont need
  src/app.ts
  src/constants/imgPaths.ts
  src/editors/appcode.ts
  src/editors/clion.ts
  src/editors/datagrip.ts
  src/editors/goland.ts
  src/editors/phpstorm.ts
  src/editors/pycharm.ts
  src/editors/rider.ts
  src/editors/rubymine.ts
  src/editors/webstorm.ts
  src/imgs/wakatime-16x16.png
  test/appcode.spec.ts
  test/clion.spec.ts
  test/datagrip.spec.ts
  test/goland.spec.ts
  test/phpstorm.spec.ts
  test/pycharm.spec.ts
  test/rider.spec.ts
  test/rubymine.spec.ts
  test/terminal.spec.ts
  test/textmate.spec.ts
  test/webstorm.spec.ts
Labels: cleanup, enhancement

#71 kakoune editor
  src/components/ActiveEditors.tsx
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/kakoune.ts
  test/kakoune.spec.ts
Labels: feature, planned

#65 Add notepad++ to the supported editors, on mac and linux it will retu…
  appveyor.yml
  src/app.ts
  src/components/ActiveEditors.tsx
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/notepadpp.ts
  test/notepadpp.spec.ts
  test/textmate.spec.ts
Labels: feature, planned

#76 fix testing for travis
  test/visual-studio.spec.ts
Labels: infrastructure

#77 Add Eric editor
  src/components/ActiveEditors.tsx
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/coda.ts
  src/editors/eric.ts
  src/editors/kakoune.ts
  test/coda.spec.ts
  test/eric.spec.ts
  test/goland.spec.ts
  test/kakoune.spec.ts
Labels: cleanup, enhancement, feature, planned

#79 Add bunch of new tests
  src/components/ActiveEditors.tsx
  src/constants/editors.ts
  src/editors/android-studio.ts
  src/editors/atom.ts
  src/editors/azure-data-studio.ts
  src/editors/blender.ts
  src/editors/brackets.ts
  src/editors/clion.ts
  src/editors/datagrip.ts
  src/editors/eric.ts
  src/editors/goland.ts
  src/editors/intellij.ts
  src/editors/kakoune.ts
  src/editors/komodo.ts
  src/editors/notepadpp.ts
  src/editors/phpstorm.ts
  src/editors/pycharm.ts
  src/editors/rider.ts
  src/editors/rubymine.ts
  src/editors/sublime-text-2.ts
  src/editors/sublime-text-3.ts
  src/editors/terminal.ts
  src/editors/vim.ts
  src/editors/visual-studio.ts
  src/editors/vscode.ts
  src/editors/webstorm.ts
  src/editors/xcode.ts
  test/android-studio.spec.ts
  test/appcode.spec.ts
  test/atom.spec.ts
  test/azure-data-studio.spec.ts
  test/blender.spec.ts
  test/clion.spec.ts
  test/coda.spec.ts
  test/datagrip.spec.ts
  test/eric.spec.ts
  test/goland.spec.ts
  test/intellij.spec.ts
  test/kakoune.spec.ts
  test/komodo.spec.ts
  test/notepadpp.spec.ts
  test/phpstorm.spec.ts
  test/pycharm.spec.ts
  test/rider.spec.ts
  test/rubymine.spec.ts
  test/sublime-text-2.spec.ts
  test/sublime-text-3.spec.ts
  test/terminal.spec.ts
  test/textmate.spec.ts
  test/unity.spec.ts
  test/vim.spec.ts
  test/visual-studio.spec.ts
  test/vscode.spec.ts
  test/webstorm.spec.ts
  test/xcode.spec.ts
Labels: IMPORTANT, cleanup, enhancement

#80 eclipse is editor installed implemented for mac
  src/editors/coda.ts
  src/editors/eclipse.ts
  src/editors/eric.ts
  src/editors/sublime-text-2.ts
  src/editors/sublime-text-3.ts
  test/eclipse.spec.ts
  test/terminal.spec.ts
Labels: bug, enhancement, planned

#81 Add Aptana Studio
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/aptana.ts
  src/editors/gedit.ts
  test/aptana.spec.ts
  test/gedit.spec.ts
Labels: bug, enhancement, feature, planned

#83 atom install
  src/editors/atom.ts
  src/editors/sublime-text-2.ts
  src/editors/sublime-text-3.ts
  test/atom.spec.ts
Labels: enhancement, feature

#84 add texstudio editor
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/texstudio.ts
  test/textstudio.spec.ts
Labels: feature, planned

#85 add install and uninstall functionality to android studio
  src/editors/android-studio.ts
Labels: enhancement, planned

#86 Add Sql Server Management Studio
  src/components/InstallEditors.tsx
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/editors/sql-server-management-studio.ts
  src/editors/visual-studio.ts
  src/editors/vscode.ts
  test/goland.spec.ts
  test/pycharm.spec.ts
  test/rider.spec.ts
  test/sql-server-management-studio.spec.ts
  test/visual-studio.spec.ts
  test/vscode.spec.ts
  test/webstorm.spec.ts
  test/xcode.spec.ts
Labels: bug, enhancement, feature, planned
