Repository wakatime/desktop, pull requests merged in 2019-08, with the labels that each got.

#20 Add electron-devtools-installer and have it install react-devtools on…
  package.json
  src/app.ts
  yarn.lock
Labels: enhancement, infrastructure

#21 Icon paths
  .eslintignore
  package.json
  scripts/createImgConstFiles.ts
  src/components/AllIconImgs.tsx
  src/constants/imgPaths.ts
  src/containers/index.tsx
  tsconfig.json
  webpack.main.config.js
  webpack.renderer.config.js
  webpack.tsconfig.json
  yarn.lock
Labels: enhancement, feature

#23 Eslint cleanup
  .gitignore
  src/app.ts
  src/editors/sublimeText2.ts
  src/editors/sublimeText3.ts
Labels: cleanup

#22 Add generated comments for generated img paths constant file
  scripts/createImgConstFiles.ts
  src/constants/imgPaths.ts
Labels: enhancement

#24 Consolidate webpack
  Procfile
  nodemon.json
  package.json
  src/app.ts
  webpack.config.js
  webpack.main.config.js
  webpack.renderer.config.js
  webpack.tsconfig.json
Labels: infrastructure

#25 modify webpack, and app to allow for import of electron
  src/app.ts
  src/containers/index.tsx
  webpack.config.js
Labels: bug

#30 Set setting for dirname only in dev mode to load extensions. This bre…
  webpack.config.js
Labels: bug

#34 Rename properties on base class Editor
  package.json
  src/editors/androidStudio.ts
  src/editors/atom.ts
  src/editors/chrome.ts
  src/editors/eclipse.ts
  src/editors/editor.ts
  src/editors/processing.ts
  src/editors/sublimeText2.ts
  src/editors/sublimeText3.ts
  src/editors/vim.ts
  src/editors/vscode.ts
  src/editors/xcode.ts
  src/lib/command-exists.ts
  test/androidStudio.spec.ts
  test/atom.spec.ts
  test/chrome.spec.ts
  test/eclipse.spec.ts
  test/processing.spec.ts
  test/sublimeText2.spec.ts
  test/sublimeText3.spec.ts
  test/vim.spec.ts
  test/vscode.spec.ts
  test/xcode.spec.ts
Labels: planned

#37 Remote redux
  .env
  Procfile
  RemoteRedux.md
  files/remote-redux-example.png
  files/remote-redux-settings.png
  package.json
  src/app.ts
  src/containers/index.tsx
  src/middlewares/crashReporter.ts
  src/middlewares/logger.ts
  src/reducers/mainProc.ts
  src/stores/mainProcStore.ts
  src/stores/rendererStore.ts
  src/utils/createReducer.ts
  src/utils/isMainProcess.ts
  src/utils/isRendererProcess.ts
  webpack.config.js
  yarn.lock
Labels: enhancement, feature
