Repository wakatime/desktop, pull requests merged in 2019-09, with the labels that each got.

#43 New Editors
  help.txt
  src/editors/android-studio.ts
  src/editors/atom.ts
  src/editors/blender.ts
  src/editors/coda.ts
  src/editors/terminal.ts
  src/editors/vim.ts
  src/editors/visual-studio.ts
  src/editors/vscode.ts
  src/editors/xcode.ts
  test/coda.spec.ts
Labels: enhancement, feature

#47 General improvements
  src/editors/brackets.ts
  src/editors/vscode.ts
  test/visual-studio.spec.ts
Labels: enhancement, feature

#46 Sebas/android studio
  src/editors/android-studio.ts
  src/editors/editor.ts
  test/android-studio.spec.ts
Labels: enhancement

#48 remove old async file dependency and use fs from node core
  package.json
  src/editors/android-studio.ts
  src/editors/atom.ts
  src/editors/chrome.ts
  src/editors/eclipse.ts
  src/editors/editor.ts
  src/editors/processing.ts
  src/editors/sublime-text-2.ts
  src/editors/sublime-text-3.ts
  src/editors/vscode.ts
  src/editors/xcode.ts
  yarn.lock
Labels: awaiting response

#49 Install button added to the UI
  src/actions/rendererActions.ts
  src/app.ts
  src/components/ActiveEditors.tsx
  src/components/Button.tsx
  src/config/editorsImgMap.ts
  src/constants/editors.ts
  src/constants/rendererActionTypes.ts
  src/containers/index.tsx
  src/editors/editor.ts
  src/reducers/editors.ts
  src/reducers/mainProc.ts
Labels: cleanup, feature, help wanted
